layout_spectrum: 0.3172043
typography_spectrum: 0.453405
color:
  saturation: 0.4219636
  lightness: 0.4074537
  brandStrength: 0.6548915
  rhythmicContrast: 0.9087281
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Sebastian Jose
